import Nav from '@/components/Nav/Nav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'JeanLaura Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className='font-sf bg-black'>
        
        <Nav/>
        

        {children}
        
        
        </body>
    </html>
  )
}
